languageCode = "en-us"
title = "Keiththomps"
baseurl = "https://keiththomps.github.io/"
description = "Learn &amp; Grow"

googleAnalytics = "UA-91413800-1"

[params]
dateformat = "Jan 2, 2006"
ampscripts = """
<script async custom-element="amp-twitter" src="https://cdn.ampproject.org/v0/amp-twitter-0.1.js"></script>
<script async custom-element="amp-iframe" src="https://cdn.ampproject.org/v0/amp-iframe-0.1.js"></script>
<script async custom-element="amp-ad" src="https://cdn.ampproject.org/v0/amp-ad-0.1.js"></script>
"""
